packages:
  - '.'
  - 'tools/publish-standard-site-documents'

catalog:
  typescript: ~5.9.2

# None of these seem to be load bearing.
allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  netlify-cli: false
  sharp: false
  unix-dgram: false

# Disable annoying ass prompt.
confirmModulesPurge: false

minimumReleaseAge: 10_080 # 7 days
minimumReleaseAgeExclude:
  - nanoid@3.3.14
  - "@rollup/rollup-android-arm-eabi@4.62.2"
  - "@rollup/rollup-android-arm64@4.62.2"
  - "@rollup/rollup-darwin-arm64@4.62.2"
  - "@rollup/rollup-darwin-x64@4.62.2"
  - "@rollup/rollup-freebsd-arm64@4.62.2"
  - "@rollup/rollup-freebsd-x64@4.62.2"
  - "@rollup/rollup-linux-arm-gnueabihf@4.62.2"
  - "@rollup/rollup-linux-arm-musleabihf@4.62.2"
  - "@rollup/rollup-linux-arm64-gnu@4.62.2"
  - "@rollup/rollup-linux-arm64-musl@4.62.2"
  - "@rollup/rollup-linux-loong64-gnu@4.62.2"
  - "@rollup/rollup-linux-loong64-musl@4.62.2"
  - "@rollup/rollup-linux-ppc64-gnu@4.62.2"
  - "@rollup/rollup-linux-ppc64-musl@4.62.2"
  - "@rollup/rollup-linux-riscv64-gnu@4.62.2"
  - "@rollup/rollup-linux-riscv64-musl@4.62.2"
  - "@rollup/rollup-linux-s390x-gnu@4.62.2"
  - "@rollup/rollup-linux-x64-gnu@4.62.2"
  - "@rollup/rollup-linux-x64-musl@4.62.2"
  - "@rollup/rollup-openbsd-x64@4.62.2"
  - "@rollup/rollup-openharmony-arm64@4.62.2"
  - "@rollup/rollup-win32-arm64-msvc@4.62.2"
  - "@rollup/rollup-win32-ia32-msvc@4.62.2"
  - "@rollup/rollup-win32-x64-gnu@4.62.2"
  - "@rollup/rollup-win32-x64-msvc@4.62.2"
  - "playwright-core@1.61.0"
  - "playwright@1.61.0"
  - "rollup@4.62.2"
  - "serialize-javascript@7.0.6"

# Disallow downgrading trust levels in a package (ex. dropping providence).
trustPolicy: no-downgrade
trustPolicyExclude:
  - "@netlify/edge-bundler@14.9.5"
  - "@netlify/images@1.2.5"
  - "@netlify/serverless-functions-api@2.10.0"
  - "@netlify/zip-it-and-ship-it@14.3.1 || 14.4.1"
  - chokidar@4.0.3
  - nanoid@3.3.14
  - semver@6.3.1
