# This workflow will do a clean install of node dependencies, build the source
# code, run tests, and deploy a preview build for the `main` branch or to prod
# for the `deploy` branch. For more information, see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main, ci, deploy ]
  pull_request:
    branches: [ main ]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        # From `.nvmrc`.
        node-version: 22.5.1

    - name: Install
      run: npm ci

    - name: Test
      run: npm test

    - name: Build
      run: npm run build:prod

    # Deploys to https://main-preview--dwac.netlify.app/.
    - name: Deploy Main
      # Only publish the `main` branch for preview.
      if: ${{ github.ref == 'refs/heads/main' }}

      # Don't use `--alias main`, as this particular alias appears to be broken.
      # My guess is that it was already used for Netlify branch builds,
      # independent of a deployment alias.
      run: |
        npm run -- netlify deploy -s "${{ secrets.NETLIFY_SITE_ID }}" \
          --alias main-preview \
          -m "Automated preview deployment from GitHub actions."
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PAT }}

    - name: Deploy Prod
      # Only publish the `deploy` branch to prod.
      if: ${{ github.ref == 'refs/heads/deploy' }}
      run: |
        npm run -- netlify deploy -s "${{ secrets.NETLIFY_SITE_ID }}" --prod \
          -m "Automated prod deployment from GitHub actions."
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PAT }}
