# This workflow will do a clean install of node dependencies, build the source
# code, run tests, and deploy a preview build for the `main` branch or to prod
# for the `deploy` branch. For more information, see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main, ci, deploy ]
  pull_request:
    branches: [ main ]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.0

    - name: Setup Node.js
      uses: actions/setup-node@v6.4.0
      with:
        # From `.nvmrc`.
        node-version: 24.17.0

    - name: Install
      run: |
        npm install -g pnpm@10.11.0
        pnpm install --frozen-lockfile
        node_modules/.bin/playwright install chromium

    - name: Test
      run: pnpm --filter="*" test

    - name: Build
      run: |
        pnpm run build:prod
        pnpm run --filter="publish-standard-site-documents" build

    # Deploys to https://main-preview--dwac.netlify.app/.
    - name: Deploy Main
      # Only publish the `main` branch for preview.
      if: ${{ github.ref == 'refs/heads/main' }}

      # Don't use `--alias main`, as this particular alias appears to be broken.
      # My guess is that it was already used for Netlify branch builds,
      # independent of a deployment alias.
      run: |
        pnpm run -- netlify deploy -s "${{ secrets.NETLIFY_SITE_ID }}" \
          --filter="dgp1130-blog" \
          --no-build \
          --alias main-preview \
          -m "Automated preview deployment from GitHub actions."
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PAT }}

    - name: Deploy Prod
      # Only publish the `deploy` branch to prod.
      if: ${{ github.ref == 'refs/heads/deploy' }}
      run: |
        pnpm run -- netlify deploy -s "${{ secrets.NETLIFY_SITE_ID }}" --prod \
          --filter="dgp1130-blog" \
          --no-build \
          -m "Automated prod deployment from GitHub actions."
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PAT }}

    - name: Publish Standard Site Documents
      # Only publish the `deploy` branch to prod.
      if: ${{ github.ref == 'refs/heads/deploy' }}
      run: |
        (cd tools/publish-standard-site-documents/ && node --enable-source-maps dist/index.js)
      env:
        ATPROTO_PASSWORD: ${{ secrets.ATPROTO_PASSWORD }}
